##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @author Yannik Köllmann (yannik.koellmann AT uni-jena.de)
# @author Jan Vogt (jan.vogt AT uni-jena.de)
# @author Mika Brückner (mika.brueckner AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/roe/Roe.cpp',
              'solvers/fwave/FWave.cpp',
              'patches/WavePropagation1d.cpp',
              'setups/dambreak/DamBreak1d.cpp',
              'setups/shockshock/ShockShock1d.cpp',
              'setups/rarerare/RareRare1d.cpp',
              'setups/subcritical1d/SubCritical1d.cpp',
              'setups/supercritical1d/SuperCritical1d.cpp',
              'setups/tsunamievent1d/TsunamiEvent1d.cpp',
              'io/Csv.cpp' ]

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone = env.Object( "main.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/roe/Roe.test.cpp',
            'solvers/fwave/FWave.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'io/Csv.test.cpp',
            'setups/dambreak/DamBreak1d.test.cpp',
            'setups/shockshock/ShockShock1d.test.cpp',
            'setups/rarerare/RareRare1d.test.cpp',
            'setups/subcritical1d/SubCritical1d.test.cpp',
            'setups/supercritical1d/SuperCritical1d.test.cpp',
            'setups/tsunamievent1d/TsunamiEvent1d.test.cpp']

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')
