##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons
          sudo apt-get install valgrind
          sudo apt-get install cppcheck
          git submodule init
          git submodule update

      - name: Style Check
        run: |
          sudo apt-get install -y clang-format
          find src/ -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Unit Tests
        run: |
          scons mode=debug
          ./build/tests

      - name: Sanitize
        run: |
          scons mode=debug+san
          ./build/tests
          ./build/tsunami_lab 25
          scons mode=release+san
          ./build/tests
          ./build/tsunami_lab 500

      - name: Valgrind
        run: |
          scons mode=debug
          valgrind ./build/tests
          valgrind ./build/tsunami_lab 25

      - name: Release
        run: |
          scons
          ./build/tests
          ./build/tsunami_lab 500

  Docs:
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          pip install sphinx sphinx-rtd-theme

      - name: Build Doxygen
        run: |
          cd docs
          doxygen Doxyfile

      - name: Build Sphinx
        run: |
          cd sphinx
          make html

      - name: Combine Output
        run: |
          mkdir -p public
          cp -r sphinx/build/html/* public/
          cp -r docs/html public/doxygen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public