##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
          sudo apt-get install -y valgrind
          sudo apt-get install -y cppcheck
          sudo apt-get install -y libnetcdf-dev netcdf-bin
          git submodule init
          git submodule update

      - name: Style Check
        run: |
          sudo apt-get install -y clang-format
          find src/ -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Unit Tests
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_VIZ=OFF -G Ninja
          cmake --build build --target tests tsunami_lab -j$(nproc)
          ./build/tests

      - name: Sanitize
        run: |
          cmake -B build_san -DBUILD_MODE=debug+san -DENABLE_VIZ=OFF -G Ninja
          cmake --build build_san --target tests tsunami_lab -j$(nproc)
          ./build_san/tests
          ./build_san/tsunami_lab -n 25 -s FWave -p DamBreak 10 5 5
          cmake -B build_san_rel -DBUILD_MODE=release+san -DENABLE_VIZ=OFF -G Ninja
          cmake --build build_san_rel --target tests tsunami_lab -j$(nproc)
          ./build_san_rel/tests
          ./build_san_rel/tsunami_lab -n 500 -s FWave -p DamBreak 10 5 5

      - name: Valgrind
        run: |
          valgrind ./build/tests
          valgrind ./build/tsunami_lab -n 25 -s FWave -p DamBreak 10 5 5

      - name: Release
        run: |
          cmake -B build_rel -DCMAKE_BUILD_TYPE=Release -DENABLE_VIZ=OFF -G Ninja
          cmake --build build_rel --target tests tsunami_lab -j$(nproc)
          ./build_rel/tests
          ./build_rel/tsunami_lab -n 500 -s FWave -p DamBreak 10 5 5

  Docs:
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          pip install sphinx sphinx-rtd-theme

      - name: Build Doxygen
        run: |
          cd docs
          doxygen Doxyfile

      - name: Build Sphinx
        run: |
          cd sphinx
          make html

      - name: Combine Output
        run: |
          mkdir -p public
          cp -r sphinx/build/html/* public/
          cp -r docs/html public/doxygen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
